# Database Configuration for Windows SQL Server
# System database connection for storing user connections

databases:
  # System database connection - stores user connection configurations
  system:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "USDF11DB197\\PROD_DB01"  # Named instance
    port: 3433  # Custom port
    database: "JobScheduler"  # Will be created if doesn't exist
    trusted_connection: false  # Using SQL Server authentication
    username: "sve-devops"  # SQL Server username
    password: "Welcome@1234"  # SQL Server password
    connection_timeout: 30
    command_timeout: 300
    description: "System database for storing user connections"
    is_system_connection: true

# Connection pool settings
connection_pool:
  max_connections: 10
  min_connections: 2
  connection_lifetime: 3600  # 1 hour
  
# Retry settings for database connections
retry_settings:
  max_retries: 3
  retry_delay: 5  # seconds
  backoff_factor: 2
  
# SQL Query settings
query_settings:
  default_timeout: 300  # 5 minutes
  long_running_timeout: 1800  # 30 minutes
  batch_size: 1000
  
# Connection validation settings
validation:
  test_query: "SELECT 1"
  validate_on_borrow: true
  validation_timeout: 5