# Database Configuration for Windows SQL Server
# Support for multiple user-defined database connections

databases:
  # Default SQL Server connection
  default:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "localhost"
    port: 1433
    database: "JobScheduler"
    trusted_connection: true  # Use Windows Authentication
    username: null  # Not needed for Windows Auth
    password: null  # Not needed for Windows Auth
    connection_timeout: 30
    command_timeout: 300
    description: "Default local SQL Server"
    
  # SQL Server with SQL Authentication
  sql_auth:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "localhost"
    port: 1433
    database: "JobScheduler"
    trusted_connection: false
    username: "sa"
    password: "YourPassword123"
    connection_timeout: 30
    command_timeout: 300
    description: "Local SQL Server with SQL Auth"
    
  # Production environment example
  production:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "prod-sql-server.domain.com"
    port: 1433
    database: "ProductionDB"
    trusted_connection: true
    username: null
    password: null
    connection_timeout: 30
    command_timeout: 600
    description: "Production SQL Server"
    
  # Development environment
  development:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "dev-sql-server.domain.com"
    port: 1433
    database: "DevDB"
    trusted_connection: true
    username: null
    password: null
    connection_timeout: 30
    command_timeout: 300
    description: "Development SQL Server"
    
  # Remote SQL Server with custom port
  remote_server:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "remote-sql.company.com"
    port: 14331  # Custom port
    database: "ReportsDB"
    trusted_connection: false
    username: "reports_user"
    password: "SecurePassword123!"
    connection_timeout: 45
    command_timeout: 900
    description: "Remote Reports Database"
    
  # Named instance example
  named_instance:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "server01\\SQLEXPRESS"  # Named instance
    port: null  # Not needed for named instances
    database: "TestDB"
    trusted_connection: true
    username: null
    password: null
    connection_timeout: 30
    command_timeout: 300
    description: "SQL Server Express Named Instance"
    
  # Azure SQL Database example
  azure_sql:
    driver: "{ODBC Driver 17 for SQL Server}"
    server: "myserver.database.windows.net"
    port: 1433
    database: "AzureDB"
    trusted_connection: false
    username: "azureuser@myserver"
    password: "AzurePassword123!"
    connection_timeout: 30
    command_timeout: 300
    encrypt: true  # Required for Azure SQL
    trust_server_certificate: false
    description: "Azure SQL Database"

# Connection pool settings
connection_pool:
  max_connections: 10
  min_connections: 2
  connection_lifetime: 3600  # 1 hour
  
# Retry settings for database connections
retry_settings:
  max_retries: 3
  retry_delay: 5  # seconds
  backoff_factor: 2
  
# SQL Query settings
query_settings:
  default_timeout: 300  # 5 minutes
  long_running_timeout: 1800  # 30 minutes
  batch_size: 1000
  
# Connection validation settings
validation:
  test_query: "SELECT 1"
  validate_on_borrow: true
  validation_timeout: 5