2a73019b-d0ba-4091-9ccb-46fdba284468:
  connection_name: system
  connection_string: null
  created_date: '2025-08-24T01:31:48.118622'
  current_status: pending
  database_name: null
  description: Testing execution in London timezone
  enabled: true
  fetch_size: 1000
  is_running: false
  job_id: 2a73019b-d0ba-4091-9ccb-46fdba284468
  job_type: sql
  last_run_time: null
  max_retries: 3
  max_rows: 10000
  metadata: {}
  modified_date: '2025-08-24T01:31:48.118622'
  name: London Timezone Test Job
  next_run_time: null
  query_timeout: 300
  retry_count: 0
  retry_delay: 60
  run_as: null
  sql_query: SELECT GETUTCDATE() as utc_time, GETDATE() as local_time, 'London execution
    test' as message
  timeout: 30
5973ffc4-9a87-4dc7-985c-5865528e3cd2:
  connection_name: system
  connection_string: null
  created_date: '2025-08-24T01:32:53.263120'
  current_status: pending
  database_name: null
  description: Testing execution in Europe/London
  enabled: true
  fetch_size: 1000
  is_running: false
  job_id: 5973ffc4-9a87-4dc7-985c-5865528e3cd2
  job_type: sql
  last_run_time: null
  max_retries: 3
  max_rows: 10000
  metadata: {}
  modified_date: '2025-08-24T01:32:53.263120'
  name: Multi-TZ Test Europe/London
  next_run_time: null
  query_timeout: 300
  retry_count: 0
  retry_delay: 60
  run_as: null
  sql_query: SELECT GETUTCDATE() as utc_time, 'Europe/London' as timezone_test
  timeout: 30
