# Logging Configuration for Job Scheduler V2
# Comprehensive logging setup with timezone-aware logging

version: 1
disable_existing_loggers: false

formatters:
  timezone_formatter:
    format: '[{asctime}][{timezone}][{levelname}][{name}] {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'
    
  job_detail_formatter:
    format: '[{asctime}] {levelname}: {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S.%f'
    
  performance_formatter:
    format: '[{asctime}][{metric_type}] {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'
    
  audit_formatter:
    format: '[{asctime}][AUDIT][{levelname}] {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'
    
  system_formatter:
    format: '[{asctime}][{name}][{levelname}] {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  # System-wide logging
  system_file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/system/scheduler.log
    when: midnight
    interval: 1
    backupCount: 30
    formatter: system_formatter
    level: INFO
    encoding: utf-8
    
  # API access logging
  api_file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/system/api.log
    when: midnight
    interval: 1
    backupCount: 30
    formatter: system_formatter
    level: INFO
    encoding: utf-8
    
  # Error logging
  error_file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/system/errors.log
    when: midnight
    interval: 1
    backupCount: 90
    formatter: system_formatter
    level: ERROR
    encoding: utf-8
    
  # Performance logging
  performance_file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/performance/system_performance.log
    when: midnight
    interval: 1
    backupCount: 365
    formatter: performance_formatter
    level: INFO
    encoding: utf-8
    
  # Audit logging
  audit_file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/audit/execution_audit.log
    when: midnight
    interval: 1
    backupCount: 2555  # 7 years for compliance
    formatter: audit_formatter
    level: INFO
    encoding: utf-8
    
  # Console logging for development
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: system_formatter
    level: DEBUG

loggers:
  # Core V2 loggers
  core.v2:
    handlers: [system_file, console]
    level: INFO
    propagate: false
    
  # Timezone logging
  timezone:
    handlers: [system_file]
    level: INFO
    propagate: false
    
  # Job logging
  job_logger:
    handlers: []  # Job loggers create their own files
    level: DEBUG
    propagate: false
    
  # Performance logging
  performance:
    handlers: [performance_file]
    level: INFO
    propagate: false
    
  # Audit logging
  audit:
    handlers: [audit_file]
    level: INFO
    propagate: false
    
  # API logging
  api:
    handlers: [api_file, console]
    level: INFO
    propagate: false
    
  # Error logging
  error:
    handlers: [error_file, console]
    level: ERROR
    propagate: false
    
  # Flask application logging
  flask:
    handlers: [api_file]
    level: INFO
    propagate: false
    
  # Database logging
  database:
    handlers: [system_file]
    level: INFO
    propagate: false

# Root logger configuration
root:
  level: INFO
  handlers: [system_file, console]

# Log rotation and cleanup settings
rotation:
  timezone_logs:
    when: midnight
    interval: 1
    backup_count: 90
    
  job_detail_logs:
    when: midnight
    interval: 1
    backup_count: 180
    
  performance_logs:
    when: midnight
    interval: 1
    backup_count: 365
    
  audit_logs:
    when: midnight
    interval: 1
    backup_count: 2555

# Log level configuration by environment
environments:
  development:
    root_level: DEBUG
    console_level: DEBUG
    file_level: INFO
    
  production:
    root_level: INFO
    console_level: WARNING
    file_level: INFO
    
  testing:
    root_level: WARNING
    console_level: ERROR
    file_level: WARNING